apiVersion: v1
kind: Service
metadata:
  name: vllm-llama3-service
  namespace: llm
  labels:
    app: vllm-llama3
    vllm.role: small-model
spec:
  type: ClusterIP
  selector:
    app: vllm-llama3
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
