apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-llama3
  namespace: llm
  labels:
    app: vllm-llama3
    vllm.role: small-model
spec:
  selector:
    matchLabels:
      app: vllm-llama3
  namespaceSelector:
    matchNames:
      - llm
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      honorLabels: false
