apiVersion: v1
kind: Service
metadata:
  name: vllm-qwen14b-service
  namespace: llm
  labels:
    app: vllm-qwen14b
    vllm.role: large-model
spec:
  type: ClusterIP
  selector:
    app: vllm-qwen14b
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
